//PRODUCTS
export const FETCH_ALL_PROJECTS = "FETCH_ALL_PROJECTS";
export const FETCH_ALL_PROJECTS_ERRORS = "FETCH_ALL_PROJECTS_ERROS";
export const FETCH_SINGLE_PROJECT = "FETCH_SINGLE_PROJECT";
export const CREATE_PROJECT = "CREATE_PROJECT";
//COMMENTS
export const FETCH_EXPENSES = "FETCH_EXPENSES";

//INCOME
export const CREATE_INCOME = "CREATE_INCOME";

//EXPENSES
export const CREATE_EXPENSE = "CREATE_EXPENSE";
